# Generated by Django 4.2.4 on 2023-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminstaff',
            name='role',
            field=models.CharField(default='adminstaff', max_length=10),
        ),
        migrations.AddField(
            model_name='parent',
            name='role',
            field=models.CharField(default='parent', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(default='teacher', max_length=10),
        ),
    ]
