# Generated by Django 4.2.4 on 2023-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adminstaff_role_parent_role_student_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classesTaught',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classTaught',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
